ARG IMAGE_BASE

FROM ${IMAGE_BASE}

ARG MINECRAFT_VERSION

RUN apk update \
	&& apk add \
		bash \
		curl \
		openjdk8-jre

WORKDIR /usr/local/share/java

RUN curl -L https://launcher.mojang.com/v1/objects/${MINECRAFT_VERSION}/server.jar -o mcs

WORKDIR /root

RUN mkdir -p /run/mcs
RUN echo "eula=true" > eula.txt

ENV JAVA_INITIAL_MEMORY_ALLOCATION_POOL=1024M
ENV JAVA_MAXIMUM_MEMORY_ALLOCATION_POOL=1024M

ENTRYPOINT if test -f /etc/mcs/server.properties; then cp /etc/mcs/server.properties server.properties; fi; \
	java -Xms${JAVA_INITIAL_MEMORY_ALLOCATION_POOL} -Xmx${JAVA_MAXIMUM_MEMORY_ALLOCATION_POOL} -jar /usr/local/share/java/mcs --nogui --universe /run/mcs
